version: "3.8"
services:
  gnuboard-g6:
    restart: always
    build:
      context: .
      dockerfile: Full.Dockerfile
    volumes:
      - gnuboard6-data-dev:/g6/data
    ports:
      - "8000:8000"

volumes:
  gnuboard6-data-dev:
