"""member

Revision ID: 368ea2db5133
Revises: 1d302b9739e0
Create Date: 2023-10-05 15:37:24.599415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '368ea2db5133'
down_revision: Union[str, None] = '1d302b9739e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g6_member', 'mb_today_login',
               existing_type=mysql.VARCHAR(length=19),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('g6_member', 'mb_datetime',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('g6_member', 'mb_email_certify',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('g6_member', 'mb_open_date',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g6_member', 'mb_open_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('g6_member', 'mb_email_certify',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('g6_member', 'mb_datetime',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('g6_member', 'mb_today_login',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=19),
               existing_nullable=False)

    # ### end Alembic commands ###
