"""member_email_none_unique

Revision ID: 3a28dcc880b1
Revises: e0515ff0906b
Create Date: 2023-10-16 16:14:09.781789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a28dcc880b1'
down_revision: Union[str, None] = 'e0515ff0906b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mb_email', table_name='g6_member')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mb_email', 'g6_member', ['mb_email'], unique=False)
    # ### end Alembic commands ###
