"""fix nick_date type date

Revision ID: b8b90fbaed64
Revises: 3a28dcc880b1
Create Date: 2023-10-19 17:05:41.490129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8b90fbaed64'
down_revision: Union[str, None] = '3a28dcc880b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g6_member', 'mb_nick_date',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g6_member', 'mb_nick_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
