"""me_memo

Revision ID: e0515ff0906b
Revises: 368ea2db5133
Create Date: 2023-10-16 15:23:21.915570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0515ff0906b'
down_revision: Union[str, None] = '368ea2db5133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('g6_member', 'mb_datetime',
               existing_type=mysql.DATETIME(),
               comment='회원가입일',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g6_member', 'mb_datetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='회원가입일',
               existing_nullable=False)

    # ### end Alembic commands ###
