"""me_memo

Revision ID: e0515ff0906b
Revises: 368ea2db5133
Create Date: 2023-10-16 15:23:21.915570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0515ff0906b'
down_revision: Union[str, None] = '368ea2db5133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('g6_board', 'bo_1_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_2_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_3_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_4_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_5_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_6_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_7_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_8_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_9_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_10_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_3',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_4',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_5',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_6',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_7',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_8',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_9',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_board', 'bo_10',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_config', 'cf_use_homepage',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('g6_config', 'cf_10',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('g6_member', 'mb_datetime',
               existing_type=mysql.DATETIME(),
               comment='회원가입일',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g6_member', 'mb_datetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='회원가입일',
               existing_nullable=False)
    op.alter_column('g6_config', 'cf_10',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_config', 'cf_use_homepage',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('g6_board', 'bo_10',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_9',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_8',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_7',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_6',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_5',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_4',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_3',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_10_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_9_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_8_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_7_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_6_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_5_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_4_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_3_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_2_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('g6_board', 'bo_1_subj',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    
    # ### end Alembic commands ###
